name: TicketSystem
version: '${project.version}'
main: com.github.henriquemb.ticketsystem.TicketSystem
api-version: 1.16
authors: [ henriquemb ]
commands:
  ticket:
    usage: /ticket
  tickets:
    usage: /tickets
  report:
    usage: /report
  reports:
    usage: /reports
  suggestions:
    usage: /suggestions
  suggestion:
    usage: /suggestion
  support:
    usage: /support
  ticketsystem:
    usage: ticketsystem
    aliases:
      - ts